https://github.com/codebasics/py/blob/master/ML/12_KFold_Cross_Validation/Exercise/exercise_kfold_validation.ipynb
    
    https://www.youtube.com/watch?v=gJo0uNL-5Qw&list=PLeo1K3hjS3us_ELKYSj_Fth2tIEkdKXvV&index=54

In [ ]:
# here only we apply KFold Cv inorder to check which Algo. give the best ans.,
#inshort here only the Stratified Kfold is applied in short form (cross_val_score)
#whle refrence can be taken from its parent file----> 12_k_fold

In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
iris.feature_names



['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']



Logistic Regression



In [5]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

/home/ujjwal/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [6]:
np.average(l_scores)


0.9733333333333334

Decision Tree




In [7]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [8]:
np.average(d_scores)


0.9600000000000002

Support Vector Machine (SVM)




In [9]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [10]:
np.average(s_scores)


0.9666666666666666

Random Forest



In [11]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [12]:
np.average(r_scores)


0.96

Best score so far is from SVM: 0.97344771241830064
    
    
    