In [ ]:
https://github.com/codebasics/py/blob/master/ML/12_KFold_Cross_Validation/12_k_fold.ipynb
    
    https://www.youtube.com/watch?v=gJo0uNL-5Qw&list=PLeo1K3hjS3us_ELKYSj_Fth2tIEkdKXvV&index=51

In [ ]:
KFold Cross Validation Python Tutorial



In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)


In [3]:
#Logistic Regression


lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9537037037037037

In [4]:
#SVM


svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)


0.3425925925925926

In [5]:
#Random Forest


rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

In [6]:
#     KFold cross validation



In [7]:
#Basic example


from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:

for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
get_score(SVC(), X_train, X_test, y_train, y_test)


0.9649415692821369

In [15]:
get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test)


0.9315525876460768

In [10]:
# here by using the kfold, we just determine the accuracy score of every model, which will be best suited for the training
# it is the raw code , sklearn inbuilt function is coded below (cross_val_score)
# no need to learn this code , just understand the concept
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))


In [11]:
scores_logistic


[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [12]:
scores_svm


[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [13]:
scores_rf

[0.9382303839732888, 0.9415692821368948, 0.9198664440734557]

cross_val_score function




In [16]:
from sklearn.model_selection import cross_val_score


# from here we have applied the stratified Kfold Algo

In [25]:
#Logistic regression model performance using cross_val_score

cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=5)


array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [18]:
#svm model performance using cross_val_score

cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)


array([0.38063439, 0.41068447, 0.51252087])

In [19]:
#random forest performance using cross_val_score

cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)


array([0.91986644, 0.94490818, 0.92988314])

In [ ]:
Parameter tunning using k fold cross validation



In [20]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8842706393544383

In [21]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9326567349472377

In [23]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9482402234636871

In [22]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9382371198013656

In [24]:
#Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees
#in random forest gives best result.



Exercise
Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

Logistic Regression
SVM
Decision Tree
Random Forest

solution in ----> 12_exercise_kfold_validation