https://youtu.be/KfnhNlD8WZI
    
    https://github.com/codebasics/py/blob/master/ML/4_save_model/4_save_and_load_model_using_pickle.ipynb
    
    https://youtu.be/cDwLNyvu_cw  (krish naik)

Machine Learning With Python: Save And Load Trained Model

    

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model



In [2]:

df = pd.read_csv('F:\\Jupyter_notebook\\csv_xlxs_File\\homeprices.csv')

df.head()


area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)



LinearRegression()

In [5]:
model.coef_


array([135.78767123])

In [6]:
model.intercept_


180616.43835616432

In [7]:
model.predict([[5000]])


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

Save Model To a File Using Python Pickle




In [9]:

import pickle


In [10]:
with open('model_pickle','wb') as file:    # here, model_pickle is a .pkl file ,wb is refer to writing(binary) format
    pickle.dump(model,file)   # here we dump our 'model' to 'file'



In [11]:
#Load Saved Model


with open('model_pickle','rb') as file:                # here, rb refer to reading mode
    mp = pickle.load(file)


In [12]:
mp.coef_


array([135.78767123])

In [13]:
mp.intercept_


180616.43835616432

In [14]:
mp.predict([[5000]])


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

Save Trained Model Using joblib




In [17]:
import joblib


In [18]:
joblib.dump(model, 'model_joblib')


['model_joblib']

In [19]:
#Load Saved Model

mj = joblib.load('model_joblib')



In [20]:
mj.coef_


array([135.78767123])

In [21]:
mj.intercept_


180616.43835616432

In [22]:
mj.predict([[5000]])


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])